{{- if .Values.enabled }}
apiVersion: {{ include "podsecuritypolicyversion" .}}
kind: PodSecurityPolicy
metadata:
  name: gardener.kube-system.csi-disk-plugin-alicloud
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  privileged: true
  allowPrivilegeEscalation: true
  volumes:
  - hostPath
  - secret
  hostNetwork: true
  allowedHostPaths:
  - pathPrefix: /var/lib/kubelet
  - pathPrefix: /dev
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  readOnlyRootFilesystem: false
{{- end -}}
