---
apiVersion: v1
kind: Secret
metadata:
  name: default-domain
  namespace: garden
  labels:
    garden.sapcloud.io/role: default-domain
  annotations:
    # dns.garden.sapcloud.io labels are deprecated and will be removed in a future version
    dns.garden.sapcloud.io/provider: aws-route53
    dns.garden.sapcloud.io/domain: example.com
    dns.gardener.cloud/provider: aws-route53
    dns.gardener.cloud/domain: example.com
type: Opaque
data: {}
  # Actual values here depend on the DNS extension of your choice.
  # For example, check out https://github.com/gardener/external-dns-management and find a lot of
  # example secret manifests here: https://github.com/gardener/external-dns-management/tree/master/examples
