---
apiVersion: v1
kind: Secret
metadata:
  name: internal-domain
  namespace: garden
  labels:
    garden.sapcloud.io/role: internal-domain
  annotations:
    dns.gardener.cloud/provider: unmanaged
    dns.gardener.cloud/domain: f-i-ts.io
type: Opaque
