# Secret containing cloud provider credentials for Packet project into which Shoot clusters should be provisioned.
---
apiVersion: v1
kind: Secret
metadata:
  name: core-packet
  namespace: garden-dev
  labels:
    cloudprofile.garden.sapcloud.io/name: packet # label is only meaningful for Gardener dashboard
type: Opaque
data:
  apiToken: base64(api-token)
  projectID: base64(project-id)
