---
apiVersion: v1
kind: Secret
metadata:
  name: core-metal
  namespace: garden-dev
  labels:
    cloudprofile.garden.sapcloud.io/name: metal # label is only meaningful for Gardener dashboard
type: Opaque
data:
  metalAPIURL: bWV0YWwudGVzdC5maS10cy5pbwo=
  metalAPIKey: eW91ciBzZWNyZXQgbWV0YWwgYXBpIHRva2VuCg==
