---
apiVersion: v1
kind: Secret
metadata:
  name: extensions-dns-{{ .Values.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
{{ toYaml .Values.secretData | indent 2 }}
---
apiVersion: dns.gardener.cloud/v1alpha1
kind: DNSProvider
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.provider }}
  secretRef:
    name: extensions-dns-{{ .Values.name }}
  domains:
    include:
{{ toYaml .Values.domains.include | indent 4 }}
{{- if .Values.domains.exclude }}
    exclude:
{{ toYaml .Values.domains.exclude | indent 4 }}
{{- end }}
