apiVersion: v1
kind: Service
metadata:
  name: etcd-{{ .Values.role }}-client
  namespace: {{ .Release.Namespace }}
  labels:
    app: etcd-statefulset
    role: {{ .Values.role }}
spec:
  type: ClusterIP
  sessionAffinity: None
  selector:
    app: etcd-statefulset
    role: {{ .Values.role }}
  ports:
  - name: client
    protocol: TCP
    port: 2379
    targetPort: 2379