---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dependency-watchdog-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: dependency-watchdog
data:
  dep-config.yaml: |-
      service: {{ .Values.dependencywatchdog.service.name }}
      namespace: {{ .Release.Namespace }}
      labels:
{{ toYaml .Values.dependencywatchdog.service.labels | indent 8 }}
      dependantPods:
      - name: controlplane
        selector:
          matchExpressions:
          - key: garden.sapcloud.io/role
            operator: In
            values:
            - controlplane
          - key: role
            operator: NotIn
            values:
            - main
            - events
