{{- range $index, $deployment := .Values.machineDeployments }}
---
apiVersion: machine.sapcloud.io/v1alpha1
kind: MachineDeployment
metadata:
  name: {{ $deployment.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  replicas: {{ $deployment.replicas }}
  minReadySeconds: {{ $deployment.minReadySeconds }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ $deployment.rollingUpdate.maxSurge }}
      maxUnavailable: {{ $deployment.rollingUpdate.maxUnavailable }}
  selector:
    matchLabels:
{{ toYaml $deployment.labels | indent 6 }}
  template:
    metadata:
      labels:
{{ toYaml $deployment.labels | indent 8 }}
    spec:
      class:
{{ toYaml $deployment.class | indent 8 }}
{{- if or $deployment.nodeTemplate.labels $deployment.nodeTemplate.annotations $deployment.nodeTemplate.taints }}
      nodeTemplate:
{{- if or $deployment.nodeTemplate.labels $deployment.nodeTemplate.annotations }}
        metadata:
{{- if $deployment.nodeTemplate.labels }}
          labels:
{{ toYaml $deployment.nodeTemplate.labels | indent 12 }}
{{- end }}
{{- if $deployment.nodeTemplate.annotations }}
          annotations:
{{ toYaml $deployment.nodeTemplate.annotations | indent 12 }}
{{- end }}
{{- end }}
{{- if $deployment.nodeTemplate.taints }}
        spec:
          taints:
{{ toYaml $deployment.nodeTemplate.taints | indent 10 }}
{{- end }}
{{- end }}
{{- end }}
